version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-api
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
    - "3306:3306"